#MASSE MASSE Paul-Basthylle


# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Utilisation d'une box Ubuntu 18.04 comme base
  config.vm.box = "ubuntu/bionic64"

#definition des machines

  # Machine 1: app1
  config.vm.define "app1" do |app1|
    app1.vm.hostname = "app1"
    app1.vm.network "private_network", ip: "192.168.56.10"
    app1.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

  # Machine 2: app2
  config.vm.define "app2" do |app2|
    app2.vm.hostname = "app2"
    app2.vm.network "private_network", ip: "192.168.56.20"
    app2.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

  # Machine 3: db
  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.56.30"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

  # Provisionnement avec Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "lamp.yml"
    ansible.inventory_path = "inventory"
  end
end

